### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by Hellohi3654** [customjack/Minecraft_FreeRPG_1.16#12]
```
[05:34:14 INFO]: [FreeRPG] Enabling FreeRPG v1.4.49
[05:34:14 WARN]: [FreeRPG] Could not save languages.yml to plugins/FreeRPG/languages.yml because languages.yml already exists.
[05:34:14 WARN]: [FreeRPG] Could not save advancedConfig.yml to plugins/FreeRPG/advancedConfig.yml because advancedConfig.yml already exists.
[05:34:14 INFO]: [PlaceholderAPI] Successfully registered expansion: freeRPG
[05:34:15 INFO]: [FreeRPG] Creating Leaderboard File, this may take a while...
[05:34:22 ERROR]: Error occurred while enabling FreeRPG v1.4.49 (Is it up to date?)
[05:34:22 ERROR]: Suspected Plugins:
[05:34:22 ERROR]: FreeRPG{enabled,ver=1.4.49,path=plugins/freerpg-1.4.49.jar}
[05:34:22 ERROR]: Exception details below:
java.lang.IllegalArgumentException: Comparison method violates its general contract!
at java.util.TimSort.mergeHi(TimSort.java:903) ~[?:?]
at java.util.TimSort.mergeAt(TimSort.java:520) ~[?:?]
at java.util.TimSort.mergeCollapse(TimSort.java:448) ~[?:?]
at java.util.TimSort.sort(TimSort.java:245) ~[?:?]
at java.util.Arrays.sort(Arrays.java:1515) ~[?:?]
at java.util.ArrayList.sort(ArrayList.java:1750) ~[?:?]
at mc.carlton.freerpg.playerInfo.Leaderboards.sortLeaderBoard(Leaderboards.java:159) ~[?:?]
at mc.carlton.freerpg.playerInfo.Leaderboards.sortAllLeaderBoards(Leaderboards.java:126) ~[?:?]
at mc.carlton.freerpg.serverFileManagement.LeaderBoardFilesManager.addDataToFile(LeaderBoardFilesManager.java:189) ~[?:?]
at mc.carlton.freerpg.serverFileManagement.LeaderBoardFilesManager.createLeaderBoardFile(LeaderBoardFilesManager.java:177) ~[?:?]
at mc.carlton.freerpg.FreeRPG.onEnable(FreeRPG.java:120) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-25]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-25]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-25]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:500) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-25]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:414) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-25]
at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:467) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-25]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:260) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-25]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:946) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-25]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:176) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-25]
at java.lang.Thread.run(Thread.java:834) [?:?]
[05:34:22 INFO]: [FreeRPG] Disabling FreeRPG v1.4.49
```
Server creates this error when starting

**Comment by Hellohi3654** [comment]
seems to be something to do with leaderboards.yml I tried deleting it but still got same error
