### ISSUE TITLE
ArrayOutOfBounds Exception - miscEvents/PlayerCraft.java Line:52

### ISSUE THREAD

**Issue by ProgrammingLogic** [customjack/Minecraft_FreeRPG_1.16#4]
Whenever a org.bukkit.event.inventory.CraftItemEvent occurs where the item was crafted in a 2x2 Crafting Grid, the following error occurs. 

This is the result of Line 51 of miscEvents/PlayerCraft.java, where the code presumes the size of the grid is nine, which is not always the case. Submitting a pull request to fix the issue. 

The exact stacktrace is as follows:
```
[17:14:20 ERROR]: Could not pass event CraftItemEvent to FreeRPG v1.2.10
java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
        at mc.carlton.freerpg.miscEvents.PlayerCraft.onPlayerCraft(PlayerCraft.java:52) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.2.jar:git-Paper-174]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.2.jar:git-Paper-174]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.2.jar:git-Paper-174]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.2.jar:git-Paper-174]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2422) ~[patched_1.16.2.jar:git-Paper-174]
        at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.2.jar:git-Paper-174]
        at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.2.jar:git-Paper-174]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.2.jar:git-Paper-174]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.2.jar:git-Paper-174]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.2.jar:git-Paper-174]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.2.jar:git-Paper-174]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.2.jar:git-Paper-174]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.2.jar:git-Paper-174]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.2.jar:git-Paper-174]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.2.jar:git-Paper-174]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1264) ~[patched_1.16.2.jar:git-Paper-174]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.2.jar:git-Paper-174]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-174]
        at java.lang.Thread.run(Thread.java:834) [?:?]```

**Comment by customjack** [comment]
This issue was fixed around the same time you fixed it, I just never saw your fix so I never pushed your fix.
